import type { Metadata } from "next";
import Link from "next/link";
import styles from "./terms.module.css";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Aqademiq / R13 Labs terms of use.",
};

export default function TermsPage() {
  return (
    <div style={{ background: "var(--aq-paper)", overflowX: "clip" }}>
      <div className={styles.grid}>
        <aside className={styles.toc}>
          <div className="tt">Contents</div>
          <a href="#s1">1. DEFINITIONS AND INTERPRETATION</a>
          <a href="#s2">2. CHANGES TO THE DIGITAL PLATFORM AND SERVICES</a>
          <a href="#s3">3. ELIGIBILITY, AGE VERIFICATION AND PARENTAL CONSENT</a>
          <a href="#s4">4. ACCOUNT REGISTRATION AND SECURITY</a>
          <a href="#s5">5. NATURE OF SERVICES AND NO MEDICAL CLAIMS</a>
          <a href="#s6">6. USE OF ARTIFICIAL INTELLIGENCE</a>
          <a href="#s7">7. USER-GENERATED CONTENT AND UPLOADS</a>
          <a href="#s8">8. PROHIBITED USES AND USER CONDUCT</a>
          <a href="#s9">9. INTELLECTUAL PROPERTY RIGHTS</a>
          <a href="#s10">10. THIRD-PARTY SERVICES AND LINKS</a>
          <a href="#s11">11. DISCLAIMER OF WARRANTIES</a>
          <a href="#s12">12. LIMITATION OF LIABILITY</a>
          <a href="#s13">13. INDEMNIFICATION</a>
          <a href="#s14">14. TERM AND TERMINATION</a>
          <a href="#s15">15. GOVERNING LAW AND DISPUTE RESOLUTION</a>
          <a href="#s16">16. GENERAL PROVISIONS</a>
          <a href="#s17">17. GRIEVANCE OFFICER</a>
        </aside>
        <div className="lg-main">
          <div className={styles.eyebrow}>
            <span className="e">Legal</span>
            <span className={styles.chip}>Draft</span>
          </div>
          <div id="legalbody">
            <h1 className={styles.title} id="lg-top">
              TERMS OF USE
            </h1>
            <p className={styles.p}>
              This document constitutes an electronic record in terms of the Information Technology
              Act, 2000 (&ldquo;IT Act&rdquo;), and the rules, regulations and amendments thereof, as
              applicable, and the amended provisions pertaining to electronic records in various
              statutes as amended by the IT Act. This electronic record is generated by a computer
              system and does not require any physical or digital signatures. These Terms of Use
              (&quot;Terms&quot;) govern the access to and use of the Digital Platform (as defined
              below) made available by R13 Labs India Private Limited, operating under the brand name
              &quot;Aqademiq&quot; (hereinafter referred to as &quot;Aqademiq&quot;, &quot;We&quot;,
              &quot;Us&quot; or &quot;Our&quot;). By clicking &quot;I Agree&quot;, &quot;Sign
              up&quot;, &quot;Proceed&quot;, or any similar confirmation button, or by accessing,
              browsing, registering on, downloading, or otherwise using the Digital Platform, You (as
              defined below) expressly acknowledge that You have read and understood these Terms and
              consent to be bound by them. if You do not agree to these terms, You must not access or
              use the Digital Platform.
            </p>
            <h2 className={styles.sec} id="s1">
              1. DEFINITIONS AND INTERPRETATION
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>1.1.</span>
              <div className={`${styles.t} ${styles.lab}`}>Definitions</div>
            </div>
            <p className={styles.p}>
              In these Terms, unless the context otherwise requires, the following words and
              expressions shall have the meanings set out below:
            </p>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>a)</span>
              <div className={styles.t}>
                &ldquo;Attention Deficit / Hyperactive Disorder&rdquo; means a a neurodevelopment
                condition recognised in medical and psychiatric literature. Any reference to
                Attention Deficit / Hyperactive Disorder (&ldquo;ADHD&rdquo;) in these Terms is
                descriptive only and does not constitute a diagnosis, medical opinion, or clinical
                claim by Aqademiq.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>b)</span>
              <div className={styles.t}>
                &ldquo;AI-Enabled Tools&rdquo; means any artificial intelligence, machine-learning,
                algorithmic, or automated features integrated into the Digital Platform that are used
                to generate summaries, insights, recommendations, content, analytics, or
                administrative outputs for Users, and which are provided solely for informational,
                educational, or assistive purposes, and shall not be relied upon as professional,
                therapeutic, medical, psychological, legal, or financial advice, nor shall such tools
                independently determine User rights, eligibility, or outcomes.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>c)</span>
              <div className={styles.t}>
                &quot;AI-Generated Outputs&quot; means any response, suggestion, study plan, schedule,
                or other content generated by Ada or any other AI-enabled feature of the Platform in
                response to a User&apos;s prompt or input, whether generated using models provided by
                Anthropic or any other third-party AI infrastructure provider engaged by Aqademiq.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>d)</span>
              <div className={styles.t}>
                &ldquo;Applicable Laws&quot; means all laws, rules, regulations, directions,
                notifications, orders, and guidelines in force in India, including but not limited to
                the IT Act, , the IT (Reasonable Security
              </div>
            </div>
            <p className={styles.p}>
              Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, the
              Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules,
              2021, the Digital Personal Data Protection Act, 2023, and any amendments or replacements
            </p>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>e)</span>
              <div className={styles.t}>
                &quot;Digital Platform&quot; means the technology-enabled platform operated by
                Aqademiq, comprising the Aqademiq web application accessible at [Aqademiq &mdash; AI
                Study Planner for Students Who Procrastinate | ADHD-Friendly] and mobile application,
                including the &ldquo;IOS&rdquo; and &ldquo;Android&rdquo; applications, and any related
                interfaces through which the Services are made available,.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>f)</span>
              <div className={styles.t}>
                &quot;Information&quot; means any data, content, materials, inputs, or outputs,
                including study plans, syllabi, notes, schedules, goals, text, messages, and other
                information that is: (i) provided by a User or on the User&apos;s behalf (including by
                a parent or legal guardian) to Aqademiq; (ii) generated, processed, or displayed
                through the Digital Platform (including Ada).
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>g)</span>
              <div className={styles.t}>
                &quot;Intellectual Property / Intellectual Property Rights&quot; means all
                intellectual property rights of any kind, whether registered or unregistered,
                anywhere in the world, including copyrights, moral rights, trademarks, service marks,
                trade names, trade secrets, know-how, confidential information, database rights,
                software rights, and all similar or equivalent rights, together with all applications,
                renewals, and extensions thereof.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>h)</span>
              <div className={styles.t}>
                &quot;Guest Mode&quot; means the limited, unregistered mode in which a User may explore
                certain features of the Platform prior to creating an account or providing Personal
                Data.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>i)</span>
              <div className={styles.t}>
                &quot;Platform IP&quot; means all Intellectual Property subsisting in or relating to
                the Digital Platform and Aqademiq&apos;s business, including the software, source
                code, user interface, design elements, the sound engine, content libraries, prompts,
                workflows, datasets, documentation, analytics, and all improvements, enhancements, and
                derivative works thereto.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>j)</span>
              <div className={styles.t}>
                &quot;Privacy Policy&quot; means the privacy policy issued by Aqademiq on the Digital
                Platform, as amended from time to time. For the purposes of these Terms, expressions
                relating to data protection, including &quot;Personal Data&quot;,
                &quot;Processing&quot;, &quot;Consent&quot;, &quot;Data Principal&quot;, &quot;Data
                Fiduciary&quot;, and &quot;Data Processor&quot;, shall have the meanings assigned to
                them under the Privacy Policy and Applicable Laws.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>k)</span>
              <div className={styles.t}>
                &quot;Prohibited Uses&quot; means any use of the Digital Platform that is unlawful,
                unauthorised, misleading, abusive, fraudulent, or otherwise prohibited under these
                Terms or under Applicable Laws, as further described in Section 8.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>l)</span>
              <div className={styles.t}>
                &quot;Services&quot; means the academic planning, schedule management, task tracking,
                and grade- tracking functionality offered through the Platform, together with the
                AI-enabled features
              </div>
            </div>
            <p className={styles.p}>
              provided through Ada, which operate as supplementary tools to assist Users and do not
              independently determine any User&apos;s academic outcomes, rights, or eligibility.
            </p>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>m)</span>
              <div className={styles.t}>
                &quot;Third-Party Services&quot; means any third-party technologies, large language
                models, application programming interfaces, cloud infrastructure, application stores,
                payment processors, websites, applications, tools, or resources that are integrated
                into, connected to, or accessible through the Digital Platform but that are not owned
                or controlled by Aqademiq.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>n)</span>
              <div className={styles.t}>
                &quot;User / You / Your&quot; means any individual who registers for, or otherwise
                accesses or interacts with the Platform or Services, including Users who access the
                Platform in Guest Mode.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>1.2.</span>
              <div className={`${styles.t} ${styles.lab}`}>Interpretation</div>
            </div>
            <p className={styles.p}>Unless the context otherwise requires:</p>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>a)</span>
              <div className={styles.t}>
                words importing the singular include the plural and vice versa;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>b)</span>
              <div className={styles.t}>
                headings are for convenience only and shall not affect interpretation;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>c)</span>
              <div className={styles.t}>
                the words &quot;include&quot;, &quot;includes&quot;, and &quot;including&quot; shall be
                construed as being followed by &quot;without limitation&quot;;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>d)</span>
              <div className={styles.t}>
                references to a &quot;Section&quot; refer to Sections of these Terms; and
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>e)</span>
              <div className={styles.t}>
                any reference to a statute or law includes amendments, replacements, and re-enactments
                thereof.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>1.3.</span>
              <div className={`${styles.t} ${styles.lab}`}>Changes to Terms</div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>a)</span>
              <div className={styles.t}>
                We reserve the right to modify, update, or revise these Terms from time to time. Any
                such changes shall become effective upon being posted on the Digital Platform, unless
                a later effective date is expressly stated.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>b)</span>
              <div className={styles.t}>
                Where required by Applicable Law, We will provide reasonable notice of material changes
                to these Terms through the Digital Platform or through push notifications, or such
                other channels as We may reasonably determine. Your continued access to or use of the
                Digital Platform after the effective date of any changes shall constitute Your
                acceptance of the revised Terms. If You do not agree to the modified Terms, You must
                discontinue use of the Digital Platform.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>c)</span>
              <div className={styles.t}>
                You are encouraged to review these Terms periodically, and in any event as and when
                notified by Us, to remain informed of any updates. The most current version of these
                Terms, as made available on the Platform, shall supersede all prior versions.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>d)</span>
              <div className={styles.t}>
                Any changes that result in the collection, use, or Processing of additional Personal
                Data shall be governed by the Privacy Policy.
              </div>
            </div>
            <h2 className={styles.sec} id="s2">
              2. CHANGES TO THE DIGITAL PLATFORM AND SERVICES
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>2.1.</span>
              <div className={styles.t}>
                Aqademiq may, at its sole discretion, update, modify, enhance, suspend, or discontinue
                any feature, functionality, interface, content, or component of the Digital Platform
                at any time, for purposes including, but not limited to, system maintenance, security
                enhancement, regulatory or legal compliance, performance improvement, correction of
                errors, or user-experience optimisation.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>2.2.</span>
              <div className={styles.t}>
                Where such changes materially affect paid Services, Aqademiq shall use commercially
                reasonable efforts to provide prior notice, unless the change is required on an urgent
                basis. The User acknowledges that the Digital Platform is continuously evolving, and
                Aqademiq shall not be liable for any modification, suspension, or discontinuation of
                any part of the Digital Platform or Services, except as required under Applicable Laws
                or the applicable refund policy.
              </div>
            </div>
            <h2 className={styles.sec} id="s3">
              3. ELIGIBILITY, AGE VERIFICATION AND PARENTAL CONSENT
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>3.1.</span>
              <div className={styles.t}>
                Use of the Digital Platform and the Services is available to individuals who are at
                least (18) eighteen years at least eighteen (18) years of age and who are competent to
                enter into a binding contract under Applicable Laws, The Digital Platform under
                Applicable Laws. The Digital Platform is not intended for, and must not be accessed or
                used by, any individual under the age of eighteen (18).
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>3.2.</span>
              <div className={styles.t}>
                3.2 By accessing or using the Digital Platform, the User represents and warrants that
                they are at least eighteen (18) years of age and that all information provided
                regarding their age and eligibility is true, accurate and complete.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>3.3.</span>
              <div className={styles.t}>
                3.3 Aqademiq does not undertake any independent or advance verification of a
                User&rsquo;s age or eligibility and the shall not be responsible eligibility and shall
                not be responsible or liable in any manner where a User falsifies, misrepresents, or
                provides inaccurate information regarding their age. Responsibility and liability for
                any such false or inaccurate declaration rests solely with the User and/or the person
                providing such consent, and not with us. Aqademiq shall not be responsible or liable
                in any manner where a User falsifies, misrepresents, or provides inaccurate
                information regarding their age or the existence of parental or guardian consent.
                Responsibility and liability for any such false or inaccurate declaration rests solely
                with the User and/or the person providing such consent, and not with us.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>3.4.</span>
              <div className={styles.t}>
                Aqademiq reserves the right to verify eligibility and to refuse, restrict, suspend, or
                terminate access to the Digital Platform where it reasonably believes that a User does
                not meet the eligibility or consent requirements, or where required under Applicable
                Laws.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>3.5.</span>
              <div className={styles.t}>
                If You access or use the Digital Platform on behalf of any other person (including a
                Child or dependent), You represent and warrant that You have the legal authority to
                bind such person to these Terms, and You agree to be responsible for, and to indemnify
                Aqademiq against, any loss, harm, or liability arising from such access or use.
              </div>
            </div>
            <h2 className={styles.sec} id="s4">
              4. ACCOUNT REGISTRATION AND SECURITY
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>4.1.</span>
              <div className={styles.t}>
                To access and use the Digital Platform, You may be required to create an account by
                completing the registration process, which may require You to provide certain
                Information (including Personal Data such as name, email address, age, and university
                or educational details). By registering, You acknowledge that Your account and any
                Information associated with it will be used strictly in accordance with these Terms and
                the Privacy Policy.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>4.2.</span>
              <div className={styles.t}>
                You represent and warrant that all Information provided by You is true, accurate,
                current, and complete at the time of submission, and You shall promptly update such
                Information to ensure its continued accuracy. You acknowledge that providing false,
                inaccurate, incomplete, or misleading Information may result in suspension or
                termination of access to the Digital Platform, and that we shall not be responsible or
                liable for any consequences resulting therefrom.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>4.3.</span>
              <div className={styles.t}>
                You are responsible for maintaining the confidentiality and security of Your account
                credentials, including Your username, password, registered devices, and access tokens.
                You agree not to share Your account or login credentials with, or otherwise make Your
                account available to, any other person, and You shall not sell, transfer, distribute,
                or assign Your account to any other person.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>4.4.</span>
              <div className={styles.t}>
                You shall be solely responsible for all activities that occur under Your account. To
                the maximum extent permitted by Applicable Laws, Aqademiq disclaims any liability for
                losses arising from unauthorised access to Your account resulting from Your failure to
                maintain adequate security of Your credentials, device, or access controls.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>4.5.</span>
              <div className={styles.t}>
                If You believe, or have reason to believe, that the security of Your account has been
                compromised, or that any unauthorised activity has occurred in relation to Your
                account, You shall immediately notify Us using the contact details provided on the
                Digital Platform. Upon detection of any actual or suspected security breach,
                unauthorised access, account sharing, or misuse, Aqademiq may, without prior notice and
                without liability, require You to change Your credentials, or suspend or terminate Your
                account (temporarily or permanently).
              </div>
            </div>
            <h2 className={styles.sec} id="s5">
              5. NATURE OF SERVICES AND NO MEDICAL CLAIMS
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>5.1.</span>
              <div className={styles.t}>
                The Digital Platform is a study-focused and productivity application that offers an
                ADHD- friendly interface design and a procrastination-psychology-based sound engine,
                together with AI-
              </div>
            </div>
            <p className={styles.p}>
              generated study plans and related tools, intended to assist Users in organising and
              managing their study and learning activities.
            </p>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>5.2.</span>
              <div className={styles.t}>
                The Services are positioned as wellness- and productivity-oriented technology only. The
                Digital Platform, its ADHD-friendly design, the sound engine, and all outputs of the
                AI-Enabled Tools are not clinically validated, are not medical devices, and do not
                constitute or provide medical, psychiatric, psychological, therapeutic, diagnostic, or
                clinical services. Aqademiq does not diagnose, treat, cure, mitigate, or prevent ADHD
                or any other medical, psychological, or neurological condition or disorder, and makes
                no representation or claim to that effect.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>5.3.</span>
              <div className={styles.t}>
                The design, sound engine, and features of the Digital Platform are based on research in
                psychology and productivity but have not been subject to clinical validation or
                regulatory approval. Nothing on the Digital Platform should be construed as a
                substitute for professional medical advice, diagnosis, or treatment. Users are advised
                to consult a qualified healthcare professional in relation to any medical or
                psychological condition, and never to disregard professional advice or delay seeking it
                on account of anything accessed through the Digital Platform.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>5.4.</span>
              <div className={styles.t}>
                Study plans and other outputs generated through the Services are provided for
                informational and educational purposes only. Aqademiq does not warrant or guarantee the
                accuracy, completeness, suitability, or effectiveness of any study plan or output, or
                any particular academic, learning, or performance outcome, and the ultimate
                responsibility for reviewing, evaluating, and acting upon any such output rests with
                the User.
              </div>
            </div>
            <h2 className={styles.sec} id="s6">
              6. USE OF ARTIFICIAL INTELLIGENCE
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>6.1.</span>
              <div className={styles.t}>
                The AI-Enabled Tools made available on the Digital Platform, including Ada operate as a
                custom interface, wrapper, and prompt layer built over third-party large language
                models and other Third- Party Services (which may include models provided by third
                parties such as Anthropic and OpenAI). Aqademiq does not itself develop, train, or own
                the underlying large language models and adds custom instructions, prompts, and
                safeguards on top of such third-party technologies.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>6.2.</span>
              <div className={styles.t}>
                The User acknowledges and agrees that Information manually provided by the User
                (including study plans, syllabi, and other inputs) is not used by Aqademiq to train
                general-purpose artificial intelligence models. The use of Personal Data in connection
                with the AI-Enabled Tools shall be governed by the Privacy Policy and Applicable Laws.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>6.3.</span>
              <div className={styles.t}>
                Because the AI-Enabled Tools rely on third-party models, their outputs may be variable,
                incomplete, inaccurate, or otherwise erroneous, and may include content commonly
                described as &quot;hallucinations&quot;. Aqademiq does not control such third-party
                systems and shall not be responsible
              </div>
            </div>
            <p className={styles.p}>
              for their performance, availability, or outputs. Outputs are informational and assistive
              only and are subject to the disclaimers and limitations set out in Section 14.
            </p>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>6.4.</span>
              <div className={styles.t}>
                The AI-Enabled Tools do not deploy autonomous or decision-making systems that
                independently determine any User&apos;s rights, eligibility, or other legally
                significant outcomes. The User agrees that AI-generated outputs require independent
                assessment and human oversight, that such outputs must not be blindly relied upon, and
                that the User shall exercise their own judgement and, where appropriate, seek guidance
                from qualified independent professionals before acting on any AI- generated output.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>6.5.</span>
              <div className={styles.t}>
                As Aquademiq engages with Third-Party Service Providers, the User acknowledges that
                such Third Party Service Providers are shall take reasonable steps to ensure that such
                providers are subject to their own applicable terms, safeguards, and confidentiality
                and data-protection obligations.
              </div>
            </div>
            <h2 className={styles.sec} id="s7">
              7. USER-GENERATED CONTENT AND UPLOADS
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>7.1.</span>
              <div className={styles.t}>
                The User retains ownership of the Information and content that the User submits or
                uploads to the Digital Platform. By submitting or uploading such content, the User
                grants Aqademiq a non- exclusive, worldwide, royalty-free licence to host, store,
                process, analyse, and display such content solely for the limited purpose of operating,
                providing, improving, and administering the Digital Platform and the Services, in
                accordance with the Privacy Policy and Applicable Laws.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>7.2.</span>
              <div className={styles.t}>
                The User is solely responsible for the content that the User uploads or inputs and
                represents and warrants that the User has all necessary rights to do so and that such
                content does not infringe the Intellectual Property or other rights of any third party.
                The User is advised not to upload, input, or share any sensitive, confidential,
                proprietary, or copyrighted materials belonging to the User or to any third party.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>7.3.</span>
              <div className={styles.t}>
                Aqademiq disclaims all liability for any User-uploaded content and for any misuse,
                unauthorised access, or unauthorised sharing thereof, to the maximum extent permitted
                under Applicable Laws. Complaints relating to copyright infringement or other
                objectionable content may be submitted to the Grievance Officer (&ldquo;as defined in
                the Privacy Policy&rdquo;) in accordance with Section 17; however, the User
                acknowledges that Aqademiq&apos;s ability to remediate any resulting damage may be
                limited.
              </div>
            </div>
            <h2 className={styles.sec} id="s8">
              8. PROHIBITED USES AND USER CONDUCT
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>8.1.</span>
              <div className={styles.t}>
                You shall not use the Digital Platform, the Services, or any Information for any
                unlawful, unauthorised, or Prohibited Use. Without limitation, You shall not:
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>a)</span>
              <div className={styles.t}>
                share, sell, transfer, distribute, or otherwise make available Your account or login
                credentials to any other person, or use any account other than Your own;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>b)</span>
              <div className={styles.t}>
                misuse, manipulate, or attempt to manipulate the AI-Enabled Tools, including through
                prompt injection or other techniques
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>c)</span>
              <div className={styles.t}>
                override, bypass, or subvert the instructions, prompts, safeguards, or intended
                operation of Ada or any underlying model;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>d)</span>
              <div className={styles.t}>
                hack, attempt to hack, gain or attempt to gain unauthorised access to, probe, scan, or
                test the vulnerability of the Digital Platform, its systems, servers, or any
                Information;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>e)</span>
              <div className={styles.t}>
                introduce any malware, virus, or other harmful component, or interfere with, disrupt,
                or compromise the security, integrity, or performance of the Digital Platform;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>f)</span>
              <div className={styles.t}>
                reverse engineer, decompile, scrape, extract, or misuse any part of the Digital
                Platform, the sound engine, the AI-Enabled Tools, algorithms, or other Platform IP;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>g)</span>
              <div className={styles.t}>
                impersonate any person, or submit, upload, or disseminate any false, misleading,
                infringing, or harmful Information or content; or
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>h)</span>
              <div className={styles.t}>
                engage in any activity that violates Applicable Laws or the rights of any third party.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>8.2.</span>
              <div className={styles.t}>
                Aqademiq may deploy usage analytics and pattern-detection mechanisms to identify
                unusual usage, unusual usage spikes, or other indicators of abuse or unauthorised
                activity. In the event of any Prohibited Use, or where abuse is reasonably suspected,
                Aqademiq reserves the right to suspend or terminate Your account and access to the
                Digital Platform immediately and without prior notice, to restrict future access, and,
                in connection with premium or paid features, to impose additional controls including
                internet-protocol (IP) address bans and enhanced anti-fraud and security measures.
                Aqademiq may report conduct to the relevant authorities where required under Applicable
                Laws.
              </div>
            </div>
            <h2 className={styles.sec} id="s9">
              9. INTELLECTUAL PROPERTY RIGHTS
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>9.1.</span>
              <div className={styles.t}>
                All Intellectual Property Rights, including the Platform IP, are owned by Aqademiq, its
                affiliates, or its licensors, and are protected under Applicable Laws. Nothing in these
                Terms transfers any ownership rights to the User. The User is granted only a limited,
                non-exclusive, non-transferable, revocable right to access and use the Services for
                personal, non-commercial use in accordance with these Terms.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>9.2.</span>
              <div className={styles.t}>
                The User shall retain all ownership rights in the Information submitted or uploaded by
                the User through the Digital Platform. Without affecting the User&apos;s ownership of
                such Information, the User acknowledges and agrees that, to the fullest extent permitted
                under Applicable Laws, all AI- Generated Outputs, and all insights, analytics, reports,
                and aggregated or anonymised data
              </div>
            </div>
            <p className={styles.p}>
              generated by Aqademiq through or in connection with the Digital Platform, shall vest in
              and remain the property of Aqademiq. Nothing in this clause grants Aqademiq any ownership
              of the User&apos;s underlying Information.
            </p>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>9.3.</span>
              <div className={styles.t}>
                The User shall not copy, reproduce, distribute, modify, reverse engineer, scrape,
                download, republish, transmit, or commercially exploit any part of the Digital Platform
                or the Platform IP, including the ADHD-friendly design, the sound engine, and the
                AI-Enabled Tools, without the prior written consent of Aqademiq, except as expressly
                permitted under these Terms.
              </div>
            </div>
            <h2 className={styles.sec} id="s10">
              10. THIRD-PARTY SERVICES AND LINKS
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>10.1.</span>
              <div className={styles.t}>
                The Digital Platform integrates with, connects to, or relies upon Third-Party Services,
                including third-party large language models, cloud infrastructure and hosting
                providers, application stores, and payment processors. Aqademiq does not own or control
                such Third-Party Services and shall not be responsible for their content, availability,
                security, performance, outputs, or practices.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>10.2.</span>
              <div className={styles.t}>
                Your use of any Third-Party Service is at Your own risk and is subject to the terms,
                conditions, and privacy policies of the relevant third party. The inclusion of, or
                integration with, any Third- Party Service does not imply endorsement by Aqademiq.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>10.3.</span>
              <div className={styles.t}>
                The Digital Platform may contain links to third-party websites, applications, tools, or
                resources that are not owned or controlled by Aqademiq. Aqademiq is not responsible for
                the content, availability, or practices of any such third party, and access to such
                resources is at the User&apos;s sole risk.
              </div>
            </div>
            <h2 className={styles.sec} id="s11">
              11. DISCLAIMER OF WARRANTIES
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>11.1.</span>
              <div className={styles.t}>
                To the maximum extent permitted under Applicable Laws, and notwithstanding anything
                contained elsewhere in these Terms, the Digital Platform, its features, and all content
                made available through it, including study plans, summaries, the sound engine, and any
                outputs of the AI-Enabled Tools, are provided on an &quot;as is&quot;, &quot;as
                available&quot;, and &quot;with all faults&quot; basis. Aqademiq makes no warranties or
                representations, express or implied, regarding the accuracy, completeness, timeliness,
                reliability, suitability, availability, uninterrupted operation, or error-free
                performance of the Digital Platform or any content displayed on it.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>11.2.</span>
              <div className={styles.t}>Aqademiq does not warrant that:</div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>a)</span>
              <div className={styles.t}>
                the Digital Platform will meet the User&apos;s expectations, requirements, or academic,
                learning, or personal outcomes;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>b)</span>
              <div className={styles.t}>
                any study plan, insight, summary, or AI-generated output will be accurate, complete,
                professionally validated, or fit for any particular purpose;
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>c)</span>
              <div className={styles.t}>
                the Digital Platform will be free from malware, viruses, or harmful components everytime
                the User accesses the Digital Platform; or
              </div>
            </div>
            <div className={`${styles.cl} ${styles.letter}`}>
              <span className={styles.n}>d)</span>
              <div className={styles.t}>
                data transmission over the internet will be secure, uninterrupted, or free from loss,
                corruption, or delay.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>11.3.</span>
              <div className={styles.t}>
                No Information, recommendation, study plan, or AI-generated output on the Digital
                Platform shall constitute professional, medical, psychological, or other advice,
                warranty, assurance of outcome, or fitness for any particular purpose. The System
                uptime and performance of the Digital Platform will be maintained on a commercially
                reasonable-efforts basis but cannot be guaranteed.
              </div>
            </div>
            <h2 className={styles.sec} id="s12">
              12. LIMITATION OF LIABILITY
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>12.1.</span>
              <div className={styles.t}>
                To the maximum extent permitted under Applicable Law, Aqademiq, its directors,
                officers, employees, and third-party service providers shall not be liable for any
                direct, indirect, incidental, special, consequential, punitive, exemplary, or economic
                losses, including loss of data, revenue, business or academic opportunities, or
                goodwill, arising out of or in connection with the User&apos;s access to, use of, or
                inability to use the Digital Platform or Services; reliance on any User- provided,
                third-party, or AI-generated Information, study plan, or output; Third-Party Services or
                integrations; technical failures or service interruptions; or any data loss,
                unauthorised access, or security incident, notwithstanding the implementation of
                reasonable security practices in accordance with Applicable Law.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>12.2.</span>
              <div className={styles.t}>
                Nothing in this Section shall exclude or limit any liability that cannot be excluded or
                limited under Applicable Laws .
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>12.3.</span>
              <div className={styles.t}>
                Subject to clause 12.2, the total aggregate liability of Aqademiq arising out of or in
                connection with these Terms or the use of the Digital Platform shall not exceed the
                greater of (i) the total amount paid by the User to Aqademiq in the three (3) months
                preceding the event giving rise to the claim; or (ii) ₹5,000 (Rupees Five Thousand).
              </div>
            </div>
            <h2 className={styles.sec} id="s13">
              13. INDEMNIFICATION
            </h2>
            <p className={styles.p}>
              To the maximum extent permitted under Applicable Law, You agree to defend, indemnify, and
              hold harmless Aqademiq and its affiliates, officers, directors, employees, agents, and
              third-party partners from and against any and all claims, losses, damages, liabilities,
              costs, and expenses (including reasonable legal fees) caused by or arising out of: (a)
              Your access to, use of, or misuse of the Digital Platform or the Services; (b) any breach
              or violation of these Terms by You; (c) any infringement or alleged infringement by You,
              or by any other person using Your account, of the Intellectual Property or other rights
              of any person, including in respect of content You upload; (d) any breach of Applicable
              Laws; or (e) any false, inaccurate, incomplete, or misleading Information (including any
              false declaration as to age or parental
            </p>
            <p className={styles.p}>
              consent) provided by You. Aqademiq reserves the right to assume the exclusive defence and
              control of any matter subject to indemnification, at Your cost, and You agree to
              cooperate with such defence.
            </p>
            <h2 className={styles.sec} id="s14">
              14. TERM AND TERMINATION
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>14.1.</span>
              <div className={styles.t}>
                These Terms remain valid, binding, and enforceable for as long as the User continues to
                access or use the Digital Platform, having perpetual and continuing effect, unless and
                until terminated either (a) by the User, by discontinuing all use of the Services and
                deleting their account; or (b) by Aqademiq, in accordance with these Terms.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>14.2.</span>
              <div className={styles.t}>
                Aqademiq may, at its sole discretion, suspend or terminate the User&apos;s account or
                access to the Digital Platform or Services at any time, with or without cause or prior
                notice, where the User breaches these Terms, where any Information provided by the User
                cannot be verified, or where the User&apos;s conduct is reasonably believed to be
                unlawful, fraudulent, abusive, infringing, or otherwise harmful, or where such action
                is necessary to protect the integrity, security, or functioning of the Digital Platform
                or to comply with Applicable Laws.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>14.3.</span>
              <div className={styles.t}>
                Upon termination for any reason, You must promptly cease all use of, and destroy all
                materials obtained from, the Digital Platform. Termination shall not affect any
                obligation to pay for Services already availed, or any liability that may have arisen
                under these Terms. Sections relating to Intellectual Property, disclaimers, limitation
                of liability, indemnification, and dispute resolution shall survive termination.
              </div>
            </div>
            <h2 className={styles.sec} id="s15">
              15. GOVERNING LAW AND DISPUTE RESOLUTION
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>15.1.</span>
              <div className={styles.t}>
                The User agrees to first attempt to resolve any dispute, claim, or disagreement arising
                out of or relating to the Digital Platform or the Services through good-faith
                discussions with Aqademiq by contacting the grievance or support mechanism provided on
                the Digital Platform.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>15.2.</span>
              <div className={styles.t}>
                These Terms shall be governed by and construed in accordance with the laws of India.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>15.3.</span>
              <div className={styles.t}>
                Subject to Section 20.4, the courts located at Coimbatore, India shall have exclusive
                jurisdiction over all disputes arising out of or relating to these Terms or the use of
                the Digital Platform, unless otherwise required under Applicable Laws.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>15.4.</span>
              <div className={styles.t}>
                Notwithstanding the above, Aqademiq may, at its discretion, elect to resolve any
                dispute through arbitration in accordance with the Arbitration and Conciliation Act,
                1996. The seat and venue of arbitration shall be Coimbatore, India, and the proceedings
                shall be conducted in the English language.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>15.5.</span>
              <div className={styles.t}>
                Nothing in this Section shall restrict the right of any User to approach a consumer
                forum or other authority having jurisdiction under Applicable Laws.
              </div>
            </div>
            <h2 className={styles.sec} id="s16">
              16. GENERAL PROVISIONS
            </h2>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>16.1.</span>
              <div className={styles.t}>
                Entire Agreement: These Terms, together with the Privacy Policy, the Supplemental Terms,
                and any other policies referenced herein, constitute the entire agreement between You
                and Aqademiq regarding the Digital Platform and supersede all prior understandings.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>16.2.</span>
              <div className={styles.t}>
                Severability: If any provision of these Terms is found to be invalid or unenforceable,
                the remaining provisions shall remain in full force and effect.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>16.3.</span>
              <div className={styles.t}>
                No Waiver: Aqademiq&apos;s failure to enforce any right or provision of these Terms
                shall not be considered a waiver of such right or provision.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>16.4.</span>
              <div className={styles.t}>
                Assignment: You may not assign or transfer these Terms or Your account without
                Aqademiq&apos;s prior written consent. Aqademiq may assign these Terms in connection
                with a merger, acquisition, or transfer of assets.
              </div>
            </div>
            <div className={`${styles.cl} ${styles.dec}`}>
              <span className={styles.n}>16.5.</span>
              <div className={styles.t}>
                Electronic Communications: When You use the Services or communicate with Aqademiq
                electronically, You consent to receive communications from Aqademiq electronically,
                whether by email, in-application notification, or notices posted on the Digital
                Platform, and You agree that such communications satisfy any legal requirement that they
                be in writing.
              </div>
            </div>
            <h2 className={styles.sec} id="s17">
              17. GRIEVANCE OFFICER
            </h2>
            <p className={styles.p}>
              In accordance with the Information Technology Act, 2000, the rules made thereunder, and
              the Digital Personal Data Protection Act, 2023, for any grievances, complaints, or
              concerns relating to the Digital Platform, the Services, user-uploaded content, or the
              Processing of Personal Data, Users may contact the Grievance Officer designated by
              Aqademiq, whose name and contact details are published on the Digital Platform and/or in
              the Privacy Policy: Grievance Officer: Mohammed Aswath M R13 Labs India Private Limited
              (Aqademiq) Email: <a href="mailto:support@aqademiq.com">support@aqademiq.com</a> Address:
              Amman Complex 153 - 4 to 6 , Pankaja Mill road Ramanathapuram coimbatore 641045
            </p>
          </div>
          <div className={styles.back}>
            <Link href="/">
              <span className="material-icons-outlined" style={{ fontSize: 18 }}>
                arrow_back
              </span>
              Back to home
            </Link>
            <span style={{ color: "#c0bdb6" }}>·</span>
            <Link href="/privacy">Privacy Policy</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
